// Partner control-plane: a single, typed source of truth for every partner
// relationship's real state. Production CTA components read from this registry
// and fail closed unless approval, tracking, placement eligibility, and the
// manual launch switch all agree. Current-state narrative lives in
// docs/MONETIZATION_CANONICAL_STATE.md. If the two ever disagree, reconcile
// both in the same commit.

export type PartnerStatus =
	| "discovered"
	| "verified"
	| "contacted"
	| "awaiting_response"
	| "application_started"
	| "owner_action_required"
	| "pending_approval"
	| "approved"
	| "tracking_received"
	| "ready_for_production"
	| "production_active"
	| "rejected"
	| "blocked";

export type PartnerVertical = "solar" | "battery" | "general_home_services";

export type PartnerChannel = "cpl" | "pay_per_call" | "hardware_affiliate" | "general_referral";

export type PayoutType = "per_lead" | "per_call" | "per_sale_percent" | "unknown";

export type EligiblePageType =
	| "locality_guide"
	| "state_hub"
	| "county_hub"
	| "utility_hub"
	| "battery_editorial"
	| "blog_general";

export interface Partner {
	id: string;
	name: string;
	status: PartnerStatus;
	vertical: PartnerVertical;
	channel: PartnerChannel;
	/** A tracked affiliate URL only when trackingEnabled is true. Plain untracked destinations are allowed for non-monetized relationships. */
	destination: string;
	/** Verified tracking phone number for pay-per-call partners. Undefined until a real number is received. */
	trackingPhone?: string;
	/** True only once a real attributable tracking asset exists and is approved for use. */
	trackingEnabled: boolean;
	/** True only with documentary evidence of a compensation arrangement or directly confirmed compensation mechanics. */
	compensationVerified: boolean;
	/** Whether the partner is allowed to render as a production monetization placement. */
	placementEligible: boolean;
	disclosureType: "plain_partner" | "affiliate" | "pay_per_call" | "none";
	/** Independent manual launch switch. Defaults false until the final production gate is deliberately cleared. */
	launchEnabled: boolean;
	campaignHours?: string;
	payoutType: PayoutType;
	/** Dollars for per_lead/per_call, percent for per_sale_percent. Omitted when exact value is not verified. */
	payoutValue?: number;
	currency?: "USD";
	cookieDays?: number;
	geo: string;
	trafficSources: string[];
	eligiblePageTypes: EligiblePageType[];
	lastVerified: string;
	notes?: string;
}

const ORGANIC_ONLY: string[] = ["organic_search", "content"];
const SOLAR_CPL_PAGES: EligiblePageType[] = ["locality_guide", "state_hub", "county_hub", "utility_hub"];
const LOCALITY_ONLY: EligiblePageType[] = ["locality_guide"];
const BATTERY_PAGES: EligiblePageType[] = ["battery_editorial", "blog_general"];

export const PARTNERS: Partner[] = [
	{
		id: "compare-solar-prices",
		name: "CompareSolarPrices",
		status: "owner_action_required",
		vertical: "solar",
		channel: "cpl",
		destination: "",
		trackingEnabled: false,
		compensationVerified: true,
		placementEligible: false,
		disclosureType: "affiliate",
		launchEnabled: false,
		payoutType: "per_lead",
		payoutValue: 25,
		currency: "USD",
		cookieDays: 30,
		geo: "US-CA-Southern-California",
		trafficSources: ORGANIC_ONLY,
		eligiblePageTypes: LOCALITY_ONLY,
		lastVerified: "2026-08-26",
		notes: "Direct relationship with Aaron. Confirmed $25 per qualified quote request and $200 per funded installation conversion, Southern California, 30-day click-to-quote attribution and no stated time limit on the later funded-install conversion once the GridPermit referral is attached. Dedicated ref=GridPermit plus fresh non-PII cid contract received. PayPal selected and Eyal accepted monthly qualified-lead payouts with a $100 accumulated minimum that rolls over. W-8BEN accepted for the non-U.S. individual payee. Draft PR #9 stages compliant California-only routing and fresh per-click cid generation, but production is blocked until Aaron confirms the exact PayPal setup detail, owner completes W-8BEN, current CI is green, safe outbound verification is complete and launch is deliberately enabled.",
	},
	{
		id: "energysage",
		name: "EnergySage",
		status: "owner_action_required",
		vertical: "solar",
		channel: "cpl",
		destination: "https://www.energysage.com",
		trackingEnabled: false,
		compensationVerified: false,
		placementEligible: true,
		disclosureType: "plain_partner",
		launchEnabled: false,
		payoutType: "per_lead",
		geo: "US",
		trafficSources: ORGANIC_ONLY,
		eligiblePageTypes: SOLAR_CPL_PAGES,
		lastVerified: "2026-08-26",
		notes: "CJ publisher account is activated and EnergySage advertiser ID 5835771 is known. No advertiser approval or attributable CJ link exists yet. Owner must review the current live advertiser terms and submit Apply/Join. The alternate FlexOffers route was declined at both account and verified traffic-source level with only a generic policy/current-needs reason; reconsideration was requested, so CJ is the priority. The live EnergySage destination remains the plain untracked root and must not be described as an earning link.",
	},
	{
		id: "digital-master-media",
		name: "Digital Master Media (DMM)",
		status: "owner_action_required",
		vertical: "solar",
		channel: "pay_per_call",
		destination: "",
		trackingEnabled: false,
		compensationVerified: false,
		placementEligible: false,
		disclosureType: "pay_per_call",
		launchEnabled: false,
		campaignHours: "Monday-Friday, 8:00 AM-8:00 PM EST",
		payoutType: "per_call",
		currency: "USD",
		geo: "US",
		trafficSources: ORGANIC_ONLY,
		eligiblePageTypes: LOCALITY_ONLY,
		lastVerified: "2026-08-26",
		notes: "Direct fit confirmed for organic SEO/content and nationwide U.S. solar traffic. Public offer advertises up to $53 per qualified call, but that is not a GridPermit-specific approved rate. DMM says the exact buffer depends on traffic source and is shown in the application/campaign. Abid clarified the India/Pakistan language as targeting fake callers originating outside the U.S. who pretend to be U.S. consumers, not legitimate U.S. homeowners by ethnicity; GridPermit will not target by ethnicity or national origin. Formal Publisher Application includes binding terms/signature and is now the owner-only gate. After approval, real payout, tracking number, exact buffer/IVR, ZIP guidance and disclosure/setup instructions are still required before production.",
	},
	{
		id: "bigbattery",
		name: "BigBattery",
		status: "pending_approval",
		vertical: "battery",
		channel: "hardware_affiliate",
		destination: "",
		trackingEnabled: false,
		compensationVerified: false,
		placementEligible: false,
		disclosureType: "none",
		launchEnabled: false,
		payoutType: "per_sale_percent",
		payoutValue: 5,
		geo: "US",
		trafficSources: ORGANIC_ONLY,
		eligiblePageTypes: BATTERY_PAGES,
		lastVerified: "2026-08-20",
		notes: "Application submitted and acknowledged by BigBattery. Public 5% commission. Awaiting review; do not resubmit and do not create tracking links before approval.",
	},
	{
		id: "profitise",
		name: "Profitise",
		status: "awaiting_response",
		vertical: "solar",
		channel: "cpl",
		destination: "",
		trackingEnabled: false,
		compensationVerified: false,
		placementEligible: false,
		disclosureType: "none",
		launchEnabled: false,
		payoutType: "unknown",
		geo: "US",
		trafficSources: ORGANIC_ONLY,
		eligiblePageTypes: SOLAR_CPL_PAGES,
		lastVerified: "2026-08-26",
		notes: "Current official solar PPL program supports publishers, affiliate links and lead forms and publishes a $100 minimum payout. Exact GridPermit payout is not confirmed and current official pages conflict on weekly versus bi-weekly payment cadence. Existing inquiry/follow-up is pending. Need international-publisher eligibility, a hosted click-out or otherwise low-PII model, exact geo, attribution, duplicate/reversal rules, payment/tax requirements and current agreement before owner action. See issue #14.",
	},
	{
		id: "energy-pal",
		name: "EnergyPal",
		status: "awaiting_response",
		vertical: "solar",
		channel: "cpl",
		destination: "",
		trackingEnabled: false,
		compensationVerified: false,
		placementEligible: false,
		disclosureType: "none",
		launchEnabled: false,
		payoutType: "unknown",
		geo: "US",
		trafficSources: ORGANIC_ONLY,
		eligiblePageTypes: SOLAR_CPL_PAGES,
		lastVerified: "2026-08-26",
		notes: "Current Marketing Partner signup and Publisher Agreement verified. The public agreement contains heavier lead-gen obligations including TrustedForm/Jornaya, insurance and broad compliance terms. GridPermit sent a nonbinding inquiry asking whether a tracking-link-only EnergyPal-hosted form model exists with lighter requirements, plus payout, attribution and international eligibility. Await reply; do not accept the agreement. See issue #10.",
	},
	{
		id: "solar-com-pick-my-solar",
		name: "Solar.com / Pick My Solar",
		status: "awaiting_response",
		vertical: "solar",
		channel: "cpl",
		destination: "",
		trackingEnabled: false,
		compensationVerified: false,
		placementEligible: false,
		disclosureType: "none",
		launchEnabled: false,
		payoutType: "unknown",
		geo: "US",
		trafficSources: ORGANIC_ONLY,
		eligiblePageTypes: SOLAR_CPL_PAGES,
		lastVerified: "2026-08-26",
		notes: "Official Pick My Solar publisher affiliate page was found, but the current platform and terms under Electrum/Solar.com have not yet been reconfirmed. A duplicate-checked inquiry was sent to the official listed affiliate manager asking current program status, platform, payout, payable action, attribution, international eligibility and organic/editorial acceptance. Do not use a legacy application until the current route is confirmed. See issue #11.",
	},
	{
		id: "modernize",
		name: "Modernize",
		status: "verified",
		vertical: "solar",
		channel: "cpl",
		destination: "",
		trackingEnabled: false,
		compensationVerified: false,
		placementEligible: false,
		disclosureType: "none",
		launchEnabled: false,
		payoutType: "unknown",
		geo: "US",
		trafficSources: ORGANIC_ONLY,
		eligiblePageTypes: SOLAR_CPL_PAGES,
		lastVerified: "2026-08-26",
		notes: "Current official affiliate page explicitly lists Solar as a payable lead trade and says affiliates receive links/creative, must be approved and must agree to Terms. Current consent guidance documents affiliate consent tooling and TrustedForm/Modernize consent records. Need exact Solar payout, non-U.S.-publisher eligibility, hosted-form/click-out option, attribution/duplicate/rejection rules, payment terms and live agreement before any owner application. See issue #12.",
	},
	{
		id: "home-services-lead-group",
		name: "Home Services Lead Group",
		status: "awaiting_response",
		vertical: "solar",
		channel: "cpl",
		destination: "",
		trackingEnabled: false,
		compensationVerified: false,
		placementEligible: false,
		disclosureType: "none",
		launchEnabled: false,
		payoutType: "unknown",
		geo: "US",
		trafficSources: ORGANIC_ONLY,
		eligiblePageTypes: SOLAR_CPL_PAGES,
		lastVerified: "2026-08-26",
		notes: "Current official publisher program supports Solar plus other home-services verticals, SEO/organic/content traffic, PPL/PPC, sub-IDs/UTMs and billable/rejected reporting, with campaign-specific rules. A nonbinding GridPermit inquiry was already sent and no substantive reply has arrived. Need exact solar payout, geo, qualification, tracking, payment and agreement terms before owner action. See issue #13.",
	},
	{
		id: "renogy",
		name: "Renogy",
		status: "owner_action_required",
		vertical: "battery",
		channel: "hardware_affiliate",
		destination: "",
		trackingEnabled: false,
		compensationVerified: false,
		placementEligible: false,
		disclosureType: "none",
		launchEnabled: false,
		payoutType: "per_sale_percent",
		payoutValue: 6,
		cookieDays: 27,
		geo: "US",
		trafficSources: ORGANIC_ONLY,
		eligiblePageTypes: BATTERY_PAGES,
		lastVerified: "2026-08-26",
		notes: "Renogy directly described GridPermit as a great fit, accepts international publishers with U.S.-focused audience, organic search/editorial and residential solar/battery permitting guides. Direct-confirmed U.S. rate 6%, attribution 27 days and no Renogy brand-term paid search. Official Impact application link received. Owner must review live Impact/network and advertiser terms before submission; after submission, notify Yuna because she asked to expedite approval. See issue #6.",
	},
	{
		id: "bougerv",
		name: "BougeRV",
		status: "owner_action_required",
		vertical: "battery",
		channel: "hardware_affiliate",
		destination: "",
		trackingEnabled: false,
		compensationVerified: false,
		placementEligible: false,
		disclosureType: "none",
		launchEnabled: false,
		payoutType: "per_sale_percent",
		payoutValue: 7,
		geo: "US",
		trafficSources: ORGANIC_ONLY,
		eligiblePageTypes: BATTERY_PAGES,
		lastVerified: "2026-08-26",
		notes: "BougeRV directly confirmed independent content publishers, organic/editorial traffic and contextual solar/battery/home-energy links are accepted. U.S. standard commission 7%. Official Impact application link received and deep links become available after approval. Owner must review the live Impact/network and advertiser terms before submitting. See issue #6.",
	},
	{
		id: "allpowers",
		name: "ALLPOWERS",
		status: "awaiting_response",
		vertical: "battery",
		channel: "hardware_affiliate",
		destination: "",
		trackingEnabled: false,
		compensationVerified: false,
		placementEligible: false,
		disclosureType: "none",
		launchEnabled: false,
		payoutType: "per_sale_percent",
		payoutValue: 5,
		cookieDays: 30,
		geo: "US",
		trafficSources: ORGANIC_ONLY,
		eligiblePageTypes: BATTERY_PAGES,
		lastVerified: "2026-08-26",
		notes: "ALLPOWERS directly confirmed CJ or GoAffPro accepts U.S.-audience content publishers, an international publisher with primarily U.S. organic-search traffic is eligible, current U.S. terms are 5% and 30 days, and there are no extra editorial/review requirements. Direct GoAffPro route is verified. Follow-up asking the preferred activation path is pending; owner reviews any live join/signup terms before submission. See issue #7.",
	},
	{
		id: "goal-zero",
		name: "Goal Zero",
		status: "owner_action_required",
		vertical: "battery",
		channel: "hardware_affiliate",
		destination: "",
		trackingEnabled: false,
		compensationVerified: false,
		placementEligible: false,
		disclosureType: "none",
		launchEnabled: false,
		payoutType: "per_sale_percent",
		payoutValue: 10,
		cookieDays: 30,
		geo: "US",
		trafficSources: ORGANIC_ONLY,
		eligiblePageTypes: BATTERY_PAGES,
		lastVerified: "2026-08-26",
		notes: "Official direct program publishes dynamic commission up to 10% and 30-day cookie and is managed through Partnerize. Dedicated business registration route verified; live form includes Israel, U.S. customer reach and Content promotion. Registration requires binding Partnerize/Pepperjam agreement plus payment/tax fields, so owner action is required. No tracking link exists. See issue #8.",
	},
	{
		id: "power-queen",
		name: "Power Queen",
		status: "awaiting_response",
		vertical: "battery",
		channel: "hardware_affiliate",
		destination: "",
		trackingEnabled: false,
		compensationVerified: false,
		placementEligible: false,
		disclosureType: "none",
		launchEnabled: false,
		payoutType: "per_sale_percent",
		payoutValue: 5.5,
		cookieDays: 30,
		geo: "US",
		trafficSources: ORGANIC_ONLY,
		eligiblePageTypes: BATTERY_PAGES,
		lastVerified: "2026-08-25",
		notes: "Direct GoAffPro route verified. Published 5.5% base and 30-day cookie. Existing inquiry asks for GridPermit-specific eligibility/current terms; await reply before account creation.",
	},
	{
		id: "bluetti",
		name: "BLUETTI",
		status: "awaiting_response",
		vertical: "battery",
		channel: "hardware_affiliate",
		destination: "",
		trackingEnabled: false,
		compensationVerified: false,
		placementEligible: false,
		disclosureType: "none",
		launchEnabled: false,
		payoutType: "per_sale_percent",
		payoutValue: 10,
		cookieDays: 30,
		geo: "US",
		trafficSources: ORGANIC_ONLY,
		eligiblePageTypes: BATTERY_PAGES,
		lastVerified: "2026-08-25",
		notes: "Impact alternate exists. Published terms up to 10% and 30-day cookie. Direct outreach sent; no approval or tracking link yet.",
	},
	{
		id: "ecoflow",
		name: "EcoFlow",
		status: "awaiting_response",
		vertical: "battery",
		channel: "hardware_affiliate",
		destination: "",
		trackingEnabled: false,
		compensationVerified: false,
		placementEligible: false,
		disclosureType: "none",
		launchEnabled: false,
		payoutType: "per_sale_percent",
		geo: "US",
		trafficSources: ORGANIC_ONLY,
		eligiblePageTypes: BATTERY_PAGES,
		lastVerified: "2026-08-25",
		notes: "Impact alternate exists and direct outreach was sent. Regional affiliate pages show different economics, so U.S.-specific payout/cookie remain unset until directly confirmed.",
	},
	{
		id: "redodo",
		name: "Redodo",
		status: "awaiting_response",
		vertical: "battery",
		channel: "hardware_affiliate",
		destination: "",
		trackingEnabled: false,
		compensationVerified: false,
		placementEligible: false,
		disclosureType: "none",
		launchEnabled: false,
		payoutType: "unknown",
		geo: "US",
		trafficSources: ORGANIC_ONLY,
		eligiblePageTypes: BATTERY_PAGES,
		lastVerified: "2026-08-25",
		notes: "U.S. site confirms a GoAffPro program. Existing inquiry asks international/U.S.-audience eligibility, SEO/editorial acceptance, commission, cookie, deep links and restrictions. Await reply.",
	},
	{
		id: "easunpower",
		name: "EASUNPOWER",
		status: "awaiting_response",
		vertical: "battery",
		channel: "hardware_affiliate",
		destination: "",
		trackingEnabled: false,
		compensationVerified: false,
		placementEligible: false,
		disclosureType: "none",
		launchEnabled: false,
		payoutType: "per_sale_percent",
		payoutValue: 5,
		geo: "US",
		trafficSources: ORGANIC_ONLY,
		eligiblePageTypes: BATTERY_PAGES,
		lastVerified: "2026-08-25",
		notes: "Official direct email program welcomes bloggers/content creators/site owners and publishes 5% on confirmed orders. Existing outreach asks U.S.-audience eligibility, cookie, minimums and payment methods. Await reply.",
	},
	{
		id: "vatrer-power",
		name: "Vatrer Power",
		status: "awaiting_response",
		vertical: "battery",
		channel: "hardware_affiliate",
		destination: "",
		trackingEnabled: false,
		compensationVerified: false,
		placementEligible: false,
		disclosureType: "none",
		launchEnabled: false,
		payoutType: "unknown",
		geo: "US",
		trafficSources: ORGANIC_ONLY,
		eligiblePageTypes: BATTERY_PAGES,
		lastVerified: "2026-08-25",
		notes: "Official UpPromote program supports website/blog/newsletter promotion. Existing outreach asks current U.S. commission, attribution, restrictions and payment methods. Await reply.",
	},
	{
		id: "litime",
		name: "LiTime",
		status: "awaiting_response",
		vertical: "battery",
		channel: "hardware_affiliate",
		destination: "",
		trackingEnabled: false,
		compensationVerified: false,
		placementEligible: false,
		disclosureType: "none",
		launchEnabled: false,
		payoutType: "per_sale_percent",
		payoutValue: 5,
		geo: "US",
		trafficSources: ORGANIC_ONLY,
		eligiblePageTypes: BATTERY_PAGES,
		lastVerified: "2026-08-25",
		notes: "Official program welcomes bloggers/site owners, advertises up to 5% and lists GoAffPro, Impact and Awin. Existing inquiry asks international eligibility, preferred non-Awin route, actual base/tier rate, cookie and restrictions. Await reply.",
	},
	{
		id: "rich-solar",
		name: "RICH SOLAR",
		status: "awaiting_response",
		vertical: "battery",
		channel: "hardware_affiliate",
		destination: "",
		trackingEnabled: false,
		compensationVerified: false,
		placementEligible: false,
		disclosureType: "none",
		launchEnabled: false,
		payoutType: "unknown",
		geo: "US",
		trafficSources: ORGANIC_ONLY,
		eligiblePageTypes: BATTERY_PAGES,
		lastVerified: "2026-08-25",
		notes: "Official site indicates content sites can participate. Outreach received only automated case #8058; no substantive affiliate response yet.",
	},
	{
		id: "anker-solix",
		name: "Anker SOLIX",
		status: "awaiting_response",
		vertical: "battery",
		channel: "hardware_affiliate",
		destination: "",
		trackingEnabled: false,
		compensationVerified: false,
		placementEligible: false,
		disclosureType: "none",
		launchEnabled: false,
		payoutType: "per_sale_percent",
		payoutValue: 5,
		cookieDays: 30,
		geo: "US",
		trafficSources: ORGANIC_ONLY,
		eligiblePageTypes: BATTERY_PAGES,
		lastVerified: "2026-08-25",
		notes: "Primary source lists blogs/review sites as allowed channels. Impact/LinkShare routes exist. Published 5% and 30 days. Direct outreach sent; await reply.",
	},
	{
		id: "signature-solar",
		name: "Signature Solar",
		status: "awaiting_response",
		vertical: "battery",
		channel: "hardware_affiliate",
		destination: "",
		trackingEnabled: false,
		compensationVerified: false,
		placementEligible: false,
		disclosureType: "none",
		launchEnabled: false,
		payoutType: "per_sale_percent",
		payoutValue: 9,
		cookieDays: 7,
		geo: "US",
		trafficSources: ORGANIC_ONLY,
		eligiblePageTypes: BATTERY_PAGES,
		lastVerified: "2026-08-25",
		notes: "Direct in-house program publishes up to 9% depending on product, 7-day cookie and no minimum sales requirement; official page states international referrals can earn compensation. Outreach already sent; await reply or owner direct application.",
	},
	{
		id: "natures-generator",
		name: "Nature's Generator",
		status: "awaiting_response",
		vertical: "battery",
		channel: "hardware_affiliate",
		destination: "",
		trackingEnabled: false,
		compensationVerified: false,
		placementEligible: false,
		disclosureType: "none",
		launchEnabled: false,
		payoutType: "per_sale_percent",
		payoutValue: 5,
		geo: "US",
		trafficSources: ORGANIC_ONLY,
		eligiblePageTypes: BATTERY_PAGES,
		lastVerified: "2026-08-25",
		notes: "Official affiliate page publishes 5% but references both ShareASale and Awin. Existing inquiry asks current preferred route, eligibility, cookie and restrictions. Await reply.",
	},
	{
		id: "sungoldpower",
		name: "SunGoldPower",
		status: "awaiting_response",
		vertical: "battery",
		channel: "hardware_affiliate",
		destination: "",
		trackingEnabled: false,
		compensationVerified: false,
		placementEligible: false,
		disclosureType: "none",
		launchEnabled: false,
		payoutType: "per_sale_percent",
		payoutValue: 6,
		geo: "US",
		trafficSources: ORGANIC_ONLY,
		eligiblePageTypes: BATTERY_PAGES,
		lastVerified: "2026-08-25",
		notes: "Official program publishes 6% and a ShareASale route. Existing GridPermit outreach has no substantive reply yet; cookie not confirmed.",
	},
	{
		id: "zendure",
		name: "Zendure",
		status: "awaiting_response",
		vertical: "battery",
		channel: "hardware_affiliate",
		destination: "",
		trackingEnabled: false,
		compensationVerified: false,
		placementEligible: false,
		disclosureType: "none",
		launchEnabled: false,
		payoutType: "per_sale_percent",
		cookieDays: 30,
		geo: "US",
		trafficSources: ORGANIC_ONLY,
		eligiblePageTypes: BATTERY_PAGES,
		lastVerified: "2026-08-25",
		notes: "Impact route exists. Official page conflicts between up to 5% and up to 10%, so payoutValue is intentionally unset. 30-day cookie published. Await direct clarification.",
	},
	{
		id: "growatt",
		name: "Growatt",
		status: "awaiting_response",
		vertical: "battery",
		channel: "hardware_affiliate",
		destination: "",
		trackingEnabled: false,
		compensationVerified: false,
		placementEligible: false,
		disclosureType: "none",
		launchEnabled: false,
		payoutType: "per_sale_percent",
		payoutValue: 15,
		geo: "US",
		trafficSources: ORGANIC_ONLY,
		eligiblePageTypes: BATTERY_PAGES,
		lastVerified: "2026-08-25",
		notes: "Primary source accepts publishers/content creators and publishes 15%-20% on qualifying sales with PartnerBoost/direct/Awin routes. payoutValue records only the public lower bound, not a GridPermit-approved rate. Await direct route/terms reply.",
	},
	{
		id: "eco-worthy",
		name: "ECO-WORTHY",
		status: "awaiting_response",
		vertical: "battery",
		channel: "hardware_affiliate",
		destination: "",
		trackingEnabled: false,
		compensationVerified: false,
		placementEligible: false,
		disclosureType: "none",
		launchEnabled: false,
		payoutType: "per_sale_percent",
		payoutValue: 5,
		cookieDays: 30,
		geo: "US",
		trafficSources: ORGANIC_ONLY,
		eligiblePageTypes: BATTERY_PAGES,
		lastVerified: "2026-08-25",
		notes: "Official U.S. page lists Impact/Awin and publishes 5% with 30-day cookie. Direct inquiry asks GridPermit eligibility, Impact preference, current restrictions and disclosures. Await reply.",
	},
	{
		id: "powerness",
		name: "Powerness",
		status: "awaiting_response",
		vertical: "battery",
		channel: "hardware_affiliate",
		destination: "",
		trackingEnabled: false,
		compensationVerified: false,
		placementEligible: false,
		disclosureType: "none",
		launchEnabled: false,
		payoutType: "per_sale_percent",
		payoutValue: 5,
		geo: "US",
		trafficSources: ORGANIC_ONLY,
		eligiblePageTypes: BATTERY_PAGES,
		lastVerified: "2026-08-25",
		notes: "Official page welcomes media publishers and publishes 5%, but conflicts on 45-day versus 30-day cookie. Existing inquiry asks for attribution clarification and GridPermit fit. cookieDays remains unset.",
	},
	{
		id: "acopower",
		name: "ACOPOWER",
		status: "awaiting_response",
		vertical: "battery",
		channel: "hardware_affiliate",
		destination: "",
		trackingEnabled: false,
		compensationVerified: false,
		placementEligible: false,
		disclosureType: "none",
		launchEnabled: false,
		payoutType: "unknown",
		geo: "US",
		trafficSources: ORGANIC_ONLY,
		eligiblePageTypes: BATTERY_PAGES,
		lastVerified: "2026-08-25",
		notes: "Official pages conflict materially on platform, 6% versus 8% rate and payout model. Clarification inquiry sent. Leave payout/cookie unset and do not apply until ACOPOWER resolves the conflicts.",
	},
	{
		id: "wattcycle",
		name: "WattCycle",
		status: "awaiting_response",
		vertical: "battery",
		channel: "hardware_affiliate",
		destination: "",
		trackingEnabled: false,
		compensationVerified: false,
		placementEligible: false,
		disclosureType: "none",
		launchEnabled: false,
		payoutType: "unknown",
		geo: "US",
		trafficSources: ORGANIC_ONLY,
		eligiblePageTypes: BATTERY_PAGES,
		lastVerified: "2026-08-25",
		notes: "Official U.S. affiliate page exists but public crawl does not expose commission/platform/cookie details. Inquiry sent; await reply.",
	},
	{
		id: "sok-battery",
		name: "SOK Battery",
		status: "awaiting_response",
		vertical: "battery",
		channel: "hardware_affiliate",
		destination: "",
		trackingEnabled: false,
		compensationVerified: false,
		placementEligible: false,
		disclosureType: "none",
		launchEnabled: false,
		payoutType: "unknown",
		geo: "US",
		trafficSources: ORGANIC_ONLY,
		eligiblePageTypes: BATTERY_PAGES,
		lastVerified: "2026-08-25",
		notes: "Official U.S. site exposes Affiliate Programme navigation but commercial terms are not surfaced. Direct inquiry sent; await reply.",
	},
	{
		id: "shopsolar",
		name: "ShopSolar",
		status: "awaiting_response",
		vertical: "battery",
		channel: "hardware_affiliate",
		destination: "",
		trackingEnabled: false,
		compensationVerified: false,
		placementEligible: false,
		disclosureType: "none",
		launchEnabled: false,
		payoutType: "unknown",
		geo: "US",
		trafficSources: ORGANIC_ONLY,
		eligiblePageTypes: BATTERY_PAGES,
		lastVerified: "2026-08-25",
		notes: "Official Affiliate Program redirects to a ShopSolar-branded GoAffPro signup. Existing inquiry asks publisher eligibility, SEO/editorial acceptance, current commission/cookie, deep links and restrictions. Await reply before account creation.",
	},
	{
		id: "jackery",
		name: "Jackery",
		status: "discovered",
		vertical: "battery",
		channel: "hardware_affiliate",
		destination: "",
		trackingEnabled: false,
		compensationVerified: false,
		placementEligible: false,
		disclosureType: "none",
		launchEnabled: false,
		payoutType: "unknown",
		geo: "US",
		trafficSources: ORGANIC_ONLY,
		eligiblePageTypes: [],
		lastVerified: "2026-08-25",
		notes: "Program page exists but primary commercial terms/network/geo restrictions have not yet been independently verified. Verify before outreach/application.",
	},
	{
		id: "segway-power",
		name: "Segway (portable power)",
		status: "discovered",
		vertical: "battery",
		channel: "hardware_affiliate",
		destination: "",
		trackingEnabled: false,
		compensationVerified: false,
		placementEligible: false,
		disclosureType: "none",
		launchEnabled: false,
		payoutType: "unknown",
		geo: "US",
		trafficSources: ORGANIC_ONLY,
		eligiblePageTypes: [],
		lastVerified: "2026-08-25",
		notes: "Program route exists but portable-power product commissionability is not yet verified. Verify product scope before outreach.",
	},
	{
		id: "oukitel-power",
		name: "Oukitel Power",
		status: "rejected",
		vertical: "battery",
		channel: "hardware_affiliate",
		destination: "",
		trackingEnabled: false,
		compensationVerified: false,
		placementEligible: false,
		disclosureType: "none",
		launchEnabled: false,
		payoutType: "unknown",
		geo: "US",
		trafficSources: ORGANIC_ONLY,
		eligiblePageTypes: [],
		lastVerified: "2026-08-25",
		notes: "Primary source exposes Awin as the only verified network route and no non-Awin alternate has been found. Closed unless an alternate surfaces.",
	},
	{
		id: "battle-born-batteries",
		name: "Battle Born Batteries",
		status: "rejected",
		vertical: "battery",
		channel: "hardware_affiliate",
		destination: "",
		trackingEnabled: false,
		compensationVerified: false,
		placementEligible: false,
		disclosureType: "none",
		launchEnabled: false,
		payoutType: "unknown",
		geo: "US",
		trafficSources: ORGANIC_ONLY,
		eligiblePageTypes: [],
		lastVerified: "2026-08-25",
		notes: "No live affiliate program page could be confirmed. Closed unless a current primary-source program surfaces.",
	},
	{
		id: "mighty-max-battery",
		name: "Mighty Max Battery",
		status: "rejected",
		vertical: "battery",
		channel: "hardware_affiliate",
		destination: "",
		trackingEnabled: false,
		compensationVerified: false,
		placementEligible: false,
		disclosureType: "none",
		launchEnabled: false,
		payoutType: "unknown",
		geo: "US",
		trafficSources: ORGANIC_ONLY,
		eligiblePageTypes: [],
		lastVerified: "2026-08-25",
		notes: "Current affiliate URLs are 404/unverifiable. Closed unless a live primary-source program surfaces.",
	},
	{
		id: "adt-solar",
		name: "ADT Solar",
		status: "rejected",
		vertical: "solar",
		channel: "general_referral",
		destination: "",
		trackingEnabled: false,
		compensationVerified: false,
		placementEligible: false,
		disclosureType: "none",
		launchEnabled: false,
		payoutType: "unknown",
		geo: "US",
		trafficSources: ORGANIC_ONLY,
		eligiblePageTypes: [],
		lastVerified: "2026-08-25",
		notes: "Consumer refer-a-friend structure, not a content-publisher monetization route. Closed.",
	},
	{
		id: "matchburst",
		name: "MatchBurst",
		status: "blocked",
		vertical: "solar",
		channel: "cpl",
		destination: "",
		trackingEnabled: false,
		compensationVerified: false,
		placementEligible: false,
		disclosureType: "none",
		launchEnabled: false,
		payoutType: "unknown",
		geo: "US",
		trafficSources: ORGANIC_ONLY,
		eligiblePageTypes: [],
		lastVerified: "2026-08-24",
		notes: "Awin blocked and no verified non-Awin alternate found. Park until a genuine alternate surfaces.",
	},
	{
		id: "bark",
		name: "Bark.com",
		status: "blocked",
		vertical: "general_home_services",
		channel: "general_referral",
		destination: "",
		trackingEnabled: false,
		compensationVerified: false,
		placementEligible: false,
		disclosureType: "none",
		launchEnabled: false,
		payoutType: "unknown",
		geo: "US",
		trafficSources: ORGANIC_ONLY,
		eligiblePageTypes: [],
		lastVerified: "2026-08-24",
		notes: "Awin-dependent and no verified non-Awin publisher route exists. Park.",
	},
	{
		id: "angi",
		name: "Angi",
		status: "rejected",
		vertical: "general_home_services",
		channel: "general_referral",
		destination: "",
		trackingEnabled: false,
		compensationVerified: false,
		placementEligible: false,
		disclosureType: "none",
		launchEnabled: false,
		payoutType: "unknown",
		geo: "US",
		trafficSources: ORGANIC_ONLY,
		eligiblePageTypes: [],
		lastVerified: "2026-08-19",
		notes: "Angi Affiliate Team directly confirmed it does not currently accept solar leads from affiliate partners. Closed.",
	},
	{
		id: "current-connected",
		name: "Current Connected",
		status: "rejected",
		vertical: "battery",
		channel: "hardware_affiliate",
		destination: "",
		trackingEnabled: false,
		compensationVerified: false,
		placementEligible: false,
		disclosureType: "none",
		launchEnabled: false,
		payoutType: "unknown",
		geo: "US_CA_residents_only",
		trafficSources: ORGANIC_ONLY,
		eligiblePageTypes: [],
		lastVerified: "2026-08-25",
		notes: "Program restricts applicants to U.S./Canada residents. Closed unless eligibility changes.",
	},
	{
		id: "suncheck",
		name: "SUNcheck",
		status: "rejected",
		vertical: "solar",
		channel: "cpl",
		destination: "",
		trackingEnabled: false,
		compensationVerified: false,
		placementEligible: false,
		disclosureType: "none",
		launchEnabled: false,
		payoutType: "unknown",
		geo: "US",
		trafficSources: ORGANIC_ONLY,
		eligiblePageTypes: [],
		lastVerified: "2026-08-25",
		notes: "No current real affiliate program verified and the old payout/cookie claim was invalidated. Closed.",
	},
];

/**
 * The single fail-closed launch gate. Every condition must hold before a
 * partner is allowed to render as active production monetization.
 */
export function isLaunchReady(partner: Partner): boolean {
	const hasRealTrackingAsset = partner.destination.length > 0 || Boolean(partner.trackingPhone);
	return (
		partner.status === "approved" &&
		partner.trackingEnabled === true &&
		partner.placementEligible === true &&
		partner.launchEnabled === true &&
		hasRealTrackingAsset
	);
}

/** Expected to remain empty until a partner genuinely clears every launch gate. */
export function getActivePartners(): Partner[] {
	return PARTNERS.filter(isLaunchReady);
}

export function getPartnersByChannel(channel: PartnerChannel): Partner[] {
	return PARTNERS.filter((p) => p.channel === channel);
}

export function getPartner(id: string): Partner | undefined {
	return PARTNERS.find((p) => p.id === id);
}

/** Component-facing lookup that fails closed on status, channel, tracking and launch state. */
export function getLaunchReadyPartner(id: string, expectedChannel?: PartnerChannel): Partner | null {
	const partner = getPartner(id);
	if (!partner) return null;
	if (expectedChannel && partner.channel !== expectedChannel) return null;
	if (!isLaunchReady(partner)) return null;
	return partner;
}

export type CplState = "UNTRACKED_RELATIONSHIP" | "TRACKED_UNCONFIRMED_COMPENSATION" | "APPROVED_CPL" | "ACTIVE_CPL";

export function getCplState(partner: Partner): CplState {
	if (isLaunchReady(partner)) return "ACTIVE_CPL";
	if (partner.status === "approved" && partner.trackingEnabled && partner.compensationVerified) return "APPROVED_CPL";
	if (partner.trackingEnabled) return "TRACKED_UNCONFIRMED_COMPENSATION";
	return "UNTRACKED_RELATIONSHIP";
}

export function getCplDisclosureText(state: CplState, partnerName: string): string {
	switch (state) {
		case "ACTIVE_CPL":
			return "This link may earn GridPermit a commission at no additional cost to you.";
		case "APPROVED_CPL":
			return `GridPermit has an approved partnership with ${partnerName}; tracking is not yet live on this link.`;
		case "TRACKED_UNCONFIRMED_COMPENSATION":
			return "This link is tracked; whether it results in compensation to GridPermit has not yet been confirmed.";
		case "UNTRACKED_RELATIONSHIP":
		default:
			return `GridPermit has a partner relationship with ${partnerName}; this link is not currently tracked, and whether the partnership results in compensation to GridPermit has not yet been confirmed.`;
	}
}

export function getDisclosureText(partner: Partner): string {
	if (partner.disclosureType === "none") return "";

	if (partner.disclosureType === "pay_per_call") {
		return "Calls may be recorded for quality and compliance purposes.";
	}

	if (partner.disclosureType === "affiliate" && partner.compensationVerified && partner.trackingEnabled) {
		return "This link may earn GridPermit a commission at no additional cost to you.";
	}

	if (partner.trackingEnabled && !partner.compensationVerified) {
		return "This link is tracked; whether it results in compensation to GridPermit has not yet been confirmed.";
	}

	return "GridPermit may have a commercial relationship with some third-party services; this link is not currently tracked for compensation.";
}
