import {test} from 'node:test';import assert from 'node:assert/strict';
import {readFile,mkdtemp,writeFile,rm,mkdir} from 'node:fs/promises';import path from 'node:path';import os from 'node:os';
import {debugPartnerRoutes,selectPartner,routePartnerSlot,PARTNER_CATEGORIES,PARTNER_STATUSES,campaignOpen,partnerConfigErrors} from '../src/lib/commercial/partner-platform.ts';
import {fingerprint,loadPlatformRegistry,activationPlan,atomicConfigWrite,digest} from '../scripts/lib/partner-config-io.mjs';
import {partnerConcentration,queryIntentHypothesis,normalizeNetworkReport,reportedLifecycle} from '../scripts/lib/partner-measurement.mjs';
import {managePartner} from '../scripts/partner-manage.mjs';
import {runPartnerActivation} from '../scripts/partner-activate.mjs';
import {importPartnerCsv} from '../scripts/partner-import.mjs';
import {commercialCsv} from '../scripts/lib/commercial-csv.mjs';
import {qualificationPolicy} from '../src/lib/commercial/qualification.ts';
const NOW='2026-09-26T20:00:00Z';
const base=JSON.parse(await readFile(new URL('../data/commercial/partners/compare-solar-prices.json',import.meta.url)));
function fixture(){
 const p={...structuredClone(base),partner_id:'fixture-partner',name:'Fixture partner',status:'ACTIVE',placement:'PRIMARY',categories:['PERMIT_ENGINEERING'],territories:{states:['CA'],cities:['escondido']},destination:'https://provider.example.com/permit/',paths:{solar:null,battery:null},expected_hosts:['provider.example.com'],approval_reference:'fixture-approval',qualification:{homeowner_required:true,existing_solar:'REJECT',confirmation_required:true}};
 p.program={terms_reference:'fixture:terms',reverify_after:'2026-10-20T00:00:00Z',allowed_intents:['PERMIT_ENGINEERING'],allowed_tracking_types:['CID_QUERY','UTM','PHONE_TRACKING'],excluded_cities:[],excluded_utilities:[],audience:'HOMEOWNER',allows_existing_solar:true};
 const context={state:'CA',city:'Escondido',recordId:'fixture-escondido',utility:{value:'SDGE',notes:'Verified'},pagePath:'/california/escondido/solar-permit-guide/',pageType:'locality_guide',intent:'PERMIT_ENGINEERING',pageIntent:'PERMIT_ENGINEERING'};
 const verification={reference:p.approval_reference,partner_id:p.partner_id,reviewed:true,evidence_reference:'fixture:source',approved_categories:p.categories,states:['CA'],cities:['escondido'],utilities:['VERIFIED_LOCAL_RECORD'],destinations:[p.destination],tracking_verified:true,approved_fallback:false,verified_at:'2026-09-20T00:00:00Z',expires_at:'2026-10-20T00:00:00Z',config_sha256:fingerprint(p)};
 const registry={partners:[p],verifications:[verification],health:[{url:p.destination,finalUrl:p.destination,ok:true,status:200,checkedAt:NOW,queryPreserved:null}],records:[{record_id:context.recordId,state:context.state,city:{value:context.city},utility:structuredClone(context.utility)}]};
 return {p,context,verification,registry};
}
function renew(f){f.verification.config_sha256=fingerprint(f.p);}
test('verified primary selects and registered scopes remain explicit',()=>{const f=fixture();assert.equal(selectPartner(f.context,f.registry,NOW).partner_id,f.p.partner_id);});
for(const status of PARTNER_STATUSES)test(`partner status ${status} safety`,()=>{const f=fixture();f.p.status=status;assert.equal(Boolean(selectPartner(f.context,f.registry,NOW)),status==='ACTIVE');});
for(const category of PARTNER_CATEGORIES)test(`intent ${category} cannot borrow an unrelated active partner`,()=>{const f=fixture();f.context.intent=category;f.context.pageIntent=category;assert.equal(Boolean(selectPartner(f.context,f.registry,NOW)),category==='PERMIT_ENGINEERING');});
test('50 verified partners use deterministic priority and one slot',()=>{const f=fixture();for(let i=1;i<50;i++){const p={...structuredClone(f.p),partner_id:`provider-${i}`,approval_reference:`approval-${i}`,priority:10+i};f.registry.partners.push(p);f.registry.verifications.push({...structuredClone(f.verification),partner_id:p.partner_id,reference:p.approval_reference,config_sha256:fingerprint(p)});}assert.equal(debugPartnerRoutes(f.context,f.registry,NOW).candidates.length,50);assert.equal(selectPartner(f.context,f.registry,NOW).partner_id,'fixture-partner');f.registry.partners.reverse();assert.equal(selectPartner(f.context,f.registry,NOW).partner_id,'fixture-partner');});
test('unavailable primary uses only an approved backup; equal primary rank closes',()=>{const f=fixture(),backup={...structuredClone(f.p),partner_id:'backup-provider',approval_reference:'backup-approval',placement:'BACKUP'};f.registry.partners.push(backup);f.registry.verifications.push({...structuredClone(f.verification),partner_id:backup.partner_id,reference:backup.approval_reference,config_sha256:fingerprint(backup)});f.p.status='PAUSED';assert.equal(debugPartnerRoutes(f.context,f.registry,NOW).reason,'VERIFIED_BACKUP');backup.status='SHADOW';assert.equal(selectPartner(f.context,f.registry,NOW),null);backup.status='ACTIVE';backup.placement='PRIMARY';f.p.status='ACTIVE';assert.equal(debugPartnerRoutes(f.context,f.registry,NOW).reason,'AMBIGUOUS_PRIORITY');});
test('tampered configuration cannot retain an old approval fingerprint',()=>{const f=fixture();f.p.destination='https://provider.example.com/other/';assert.ok(debugPartnerRoutes(f.context,f.registry,NOW).candidates[0].reasons.includes('APPROVAL_UNVERIFIED'));});
test('wrong city, utility, geography and Mission Viejo remain closed',async()=>{const f=fixture();f.context.utility.value='Another utility';assert.equal(debugPartnerRoutes(f.context,f.registry,NOW).reason,'CANONICAL_CONTEXT_MISMATCH');const registry=await loadPlatformRegistry(path.resolve('.'));const r=registry.records.find(r=>r.record_id==='ca-orange-mission-viejo-sce');const c={state:'CA',city:r.city.value,recordId:r.record_id,utility:r.utility,pagePath:'/california/mission-viejo/solar-permit-guide/',pageType:'locality_guide',intent:'NEW_SOLAR',pageIntent:'NEW_SOLAR'};assert.equal(selectPartner(c,registry,NOW),null);});
test('battery indication takes priority over a new-solar partner and existing solar guard remains',()=>{const f=fixture();f.context.batteryIntent='RETROFIT';assert.equal(selectPartner(f.context,f.registry,NOW),null);delete f.context.batteryIntent;f.context.existingSolar=true;assert.equal(selectPartner(f.context,f.registry,NOW),null);assert.match(qualificationPolicy(f.p).label,/does not already have solar/);});
test('approved battery adapter needs explicit retrofit eligibility and tracking',()=>{const f=fixture();f.p.categories=['BATTERY_RETROFIT'];f.p.program.allowed_intents=f.p.categories;f.verification.approved_categories=f.p.categories;f.p.qualification.existing_solar='ALLOW';f.context.intent=f.context.pageIntent='BATTERY_RETROFIT';f.context.existingSolar=true;renew(f);assert.ok(selectPartner(f.context,f.registry,NOW));f.p.tracking.active=false;renew(f);assert.equal(selectPartner(f.context,f.registry,NOW),null);});
test('CJ adapter verifies both tracking URL and approved final landing path',()=>{const f=fixture();f.p.tracking.cj_tracking_url='https://network.example.com/click-111-222';f.p.expected_hosts.push('network.example.com');f.p.paths.solar=f.p.destination;f.p.categories=['NEW_SOLAR'];f.p.program.allowed_intents=f.p.categories;f.context.intent=f.context.pageIntent='NEW_SOLAR';f.verification.approved_categories=['NEW_SOLAR'];f.verification.destinations.push(f.p.tracking.cj_tracking_url);f.registry.health=[{...f.registry.health[0],url:f.p.tracking.cj_tracking_url}];renew(f);assert.ok(selectPartner(f.context,f.registry,NOW));});
test('phone campaign enforces timezone, weekday and open interval',()=>{const p={number:'+12025550100',time_zone:'America/Los_Angeles',weekdays:[1,2,3,4,5],start:'08:00',end:'17:00',minimum_conditions:['Fixture only']};assert.ok(campaignOpen(p,'2026-09-25T18:00:00Z'));assert.equal(campaignOpen(p,NOW),false);assert.equal(campaignOpen({...p,time_zone:'unknown'},NOW),false);});
test('null verification and malformed partner fail closed',()=>{const f=fixture();f.registry.verifications=[null];assert.equal(selectPartner(f.context,f.registry,NOW),null);assert.ok(partnerConfigErrors(null).length);});
test('verified activation requires approved intent, geography, health and evidence',()=>{const f=fixture();f.p.status='APPROVED';const plan=activationPlan(f.registry,{partner:f.p.partner_id,cities:['escondido'],intent:'PERMIT_ENGINEERING',approval_reference:f.p.approval_reference,now:NOW});assert.ok(plan.ok);assert.throws(()=>activationPlan(f.registry,{partner:f.p.partner_id,cities:['unknown-city'],intent:'PERMIT_ENGINEERING',approval_reference:f.p.approval_reference,now:NOW}));});
test('atomic config apply rejects a stale expected hash',async()=>{const dir=await mkdtemp(path.join(os.tmpdir(),'partner-cas-'));try{const file=path.join(dir,'partner.json');await writeFile(file,'old');await assert.rejects(()=>atomicConfigWrite(file,'0'.repeat(64),{new:true}));assert.equal(await readFile(file,'utf8'),'old');await atomicConfigWrite(file,digest(Buffer.from('old')),{new:true});assert.deepEqual(JSON.parse(await readFile(file)),{new:true});}finally{await rm(dir,{recursive:true,force:true});}});
test('bulk import validates schema, identity and fingerprint without activating',()=>{const f=fixture(),row={partner_id:f.p.partner_id,config_json:JSON.stringify(f.p),verification_json:JSON.stringify(f.verification)};assert.equal(importPartnerCsv(commercialCsv([row]))[0].status,'REVIEWED_IMPORT_STAGED_NOT_ACTIVATED');assert.throws(()=>importPartnerCsv(commercialCsv([{...row,email:'forbidden'}])));assert.throws(()=>importPartnerCsv(commercialCsv([row,row])));});
test('concentration uses observed unique clicks; missing data remains unknown',()=>{assert.equal(partnerConcentration(null,[]).over_70_percent,null);const rows=Array.from({length:10},(_,i)=>({cid:i.toString(16).padStart(24,'0'),partner:i<8?'one':'two'}));const r=partnerConcentration([...rows,rows[0]],['one','two']);assert.equal(r.clicks,10);assert.ok(r.over_70_percent);assert.equal(r.partners[0].percent,80);});
test('query hypotheses do not classify generic battery research as new solar',()=>{assert.equal(queryIntentHypothesis('add battery to existing solar'),'BATTERY_RETROFIT');assert.equal(queryIntentHypothesis('powerwall comparison'),'UNKNOWN_BATTERY_SUBTYPE');});
test('inactive network adapters reject unreviewed columns and cannot create payments',()=>{for(const p of ['energysage','modernize','profitise'])assert.deepEqual(normalizeNetworkReport(p,[]),[]);assert.throws(()=>normalizeNetworkReport('unknown',[]));assert.equal(reportedLifecycle([],[],{}).ledger.revenue_claim,'NO_VERIFIED_PAYMENT');});

test('city and intent cohorts reuse assignment engine with safety gates',()=>{const f=fixture(),e={id:'city-experiment',status:'ACTIVE',enabled:true,eligiblePages:[f.context.pagePath],intent:'PERMIT_ENGINEERING',controlRouteId:null,variantRouteId:f.p.partner_id,startAt:'2026-09-20T00:00:00Z',endAt:'2026-10-20T00:00:00Z',assignment:'city_cohort',eligibleCities:['escondido'],variantCities:['escondido'],eligibleIntents:['PERMIT_ENGINEERING'],variantIntents:[],variantPages:[],variantBasisPoints:5000,minimumDays:28,minimumExposures:100};assert.equal(routePartnerSlot(f.context,f.registry,[e],NOW).assignment.variant,'variant');e.variantCities=[];assert.equal(routePartnerSlot(f.context,f.registry,[e],NOW).reason,'EXPERIMENT_CONTROL_NONE');e.assignment='intent_cohort';e.eligibleIntents=['PERMIT_ENGINEERING'];e.variantIntents=['PERMIT_ENGINEERING'];assert.ok(routePartnerSlot(f.context,f.registry,[e],NOW).selected);f.p.status='SHADOW';assert.equal(routePartnerSlot(f.context,f.registry,[e],NOW).selected,null);});
const productionRegistry=await loadPlatformRegistry(path.resolve('.'));
for(const partner of productionRegistry.partners)test(`registry generated: ${partner.partner_id} cannot render without all gates`,()=>{const record=productionRegistry.records.find(r=>r.record_id==='ca-san-diego-escondido-sdge');const context={state:'CA',city:record.city.value,recordId:record.record_id,utility:record.utility,pagePath:'/california/escondido/solar-permit-guide/',pageType:'locality_guide',intent:'NEW_SOLAR',pageIntent:'NEW_SOLAR'};const trial=structuredClone(productionRegistry);trial.partners.find(p=>p.partner_id===partner.partner_id).tracking.active=false;const result=debugPartnerRoutes(context,trial,NOW);assert.equal(result.candidates.find(c=>c.partner_id===partner.partner_id)?.selected??null,null);});

test('phone config rejects impossible hours, missing timezone and null placements',()=>{const f=fixture();f.p.phone={number:'+12025550100',time_zone:'America/Los_Angeles',weekdays:[1],start:'99:00',end:'99:30',minimum_conditions:[]};assert.ok(partnerConfigErrors(f.p).includes('PHONE_CAMPAIGN'));f.p.phone.start='08:00';f.p.phone.end='17:00';delete f.p.phone.time_zone;assert.ok(partnerConfigErrors(f.p).includes('PHONE_TIME_ZONE'));f.p.placements=[null];assert.ok(partnerConfigErrors(f.p).includes('INVALID_PLACEMENTS'));});
test('existing config lock is neither removed nor bypassed',async()=>{const dir=await mkdtemp(path.join(os.tmpdir(),'partner-lock-'));try{const file=path.join(dir,'p.json');await writeFile(file,'old');await writeFile(file+'.lock','other-owner');await assert.rejects(()=>atomicConfigWrite(file,digest(Buffer.from('old')),{new:true}));assert.equal(await readFile(file+'.lock','utf8'),'other-owner');assert.equal(await readFile(file,'utf8'),'old');}finally{await rm(dir,{recursive:true,force:true});}});
test('activate, pause, journal rollback and stale approval refusal apply only to isolated fixture',async()=>{const f=fixture(),root=await mkdtemp(path.join(os.tmpdir(),'partner-lifecycle-'));try{
 for(const d of ['data/localities','data/commercial/partners','data/commercial/verifications'])await mkdir(path.join(root,d),{recursive:true});
 await writeFile(path.join(root,'.git'),'gitdir: fixture-only');
 const file=path.join(root,'data/commercial/partners',f.p.partner_id+'.json');f.p.status='APPROVED';f.p.placement='PRIMARY';
 await writeFile(file,JSON.stringify(f.p));await writeFile(path.join(root,'data/localities/fixture.json'),JSON.stringify(f.registry.records[0]));await writeFile(path.join(root,'data/commercial/verifications/fixture.json'),JSON.stringify(f.verification));await writeFile(path.join(root,'data/commercial/destination-health.json'),JSON.stringify(f.registry.health));
 const args={root,partner:f.p.partner_id,cities:['escondido'],intent:'PERMIT_ENGINEERING',approval_reference:f.p.approval_reference,now:NOW};const dry=await runPartnerActivation({...args,mode:'dry-run'});assert.ok(dry.ok);const active=await runPartnerActivation({...args,mode:'apply',expectedHash:dry.current_sha256});assert.ok(active.applied);assert.equal(JSON.parse(await readFile(file)).status,'ACTIVE');
 const pauseDry=await managePartner({root,partner:f.p.partner_id,action:'pause'});const paused=await managePartner({root,partner:f.p.partner_id,action:'pause',mode:'apply',expectedHash:pauseDry.current_sha256});assert.equal(JSON.parse(await readFile(file)).status,'PAUSED');
 const restore={root,partner:f.p.partner_id,action:'rollback',snapshot:path.join(paused.journal,'before.json'),now:NOW};const plan=await managePartner(restore);assert.equal(plan.partner.status,'ACTIVE');await managePartner({...restore,mode:'apply',expectedHash:plan.current_sha256});assert.equal(JSON.parse(await readFile(file)).status,'ACTIVE');
 f.verification.reviewed=false;await writeFile(path.join(root,'data/commercial/verifications/fixture.json'),JSON.stringify(f.verification));await assert.rejects(()=>managePartner(restore),/evidence no longer valid/);
 }finally{await rm(root,{recursive:true,force:true});}});

test('vendor mapping rejects extra contact columns and requires explicit stage mapping',async()=>{const {normalizeMappedReport}=await import('../scripts/lib/partner-measurement.mjs');const map={review_reference:'fixture-review',field_map:{cid:'subid',stage:'action',channel:'channel',reported_at:'at',evidence_ref:'proof',partner_event_id:'event'},stage_map:{lead:'REFERRAL'}};const row={subid:'a'.repeat(24),action:'lead',channel:'SOLAR_QUOTE',at:NOW,proof:'fixture:report',event:'fixture:event'};assert.equal(normalizeMappedReport('energysage',[row],map)[0].stage,'REFERRAL');assert.throws(()=>normalizeMappedReport('energysage',[{...row,email:'disallowed'}],map));assert.throws(()=>normalizeMappedReport('energysage',[{...row,action:'paid'}],map));});
test('search join never invents query/page or unmatched-window attribution',async()=>{const {joinSearchPartnerResults}=await import('../scripts/lib/partner-measurement.mjs');const search=[{dimension:'PAGE',page_path:'/blog/test/',partner:'energysage',window_start:'2026-09-01',window_end:'2026-09-26'},{dimension:'QUERY',query:'battery'}],clicks=[{cid:'a'.repeat(24),partner:'energysage',page_path:'/blog/test/',timestamp:NOW}];const rows=joinSearchPartnerResults(search,clicks,{accepted:[]},{click_window_start:'2026-09-01',click_window_end:'2026-09-26'});assert.equal(rows[0].outbound_clicks,1);assert.equal(rows[0].partner_result_completeness,'PARTIAL_OR_UNKNOWN');assert.equal(rows[1].outbound_clicks,null);assert.equal(joinSearchPartnerResults(search,clicks,null,{})[0].outbound_clicks,null);});
