import {test} from 'node:test';import assert from 'node:assert/strict';
import {mkdtemp,readFile,writeFile,rm,mkdir,readdir,unlink} from 'node:fs/promises';import os from 'node:os';import path from 'node:path';
import {createOutboundHandler,recordOutbound,cleanupOutbound,eventKey,STAGES} from '../src/lib/commercial/outbound-service.mjs';
import {partnerEvidenceHold} from '../src/lib/commercial/partner-evidence-holds.ts';
const now=Date.parse('2026-09-27T01:00:00Z'),page='/california/escondido/solar-permit-guide/';
const route={partner_id:'compare-solar-prices',page_path:page,city:'Escondido',intent:'NEW_SOLAR',cta_id:'compare_solar_prices_locality',qualification_required:true,valid_until:'2026-10-10T00:00:00Z',url_template:'https://www.comparesolarprices.net/?ref=GridPermit&cid='+ '0'.repeat(24)+'#quote'};
const event={stage:'OUTBOUND_RECORDED',cid:'e101'+'a'.repeat(20),partner_id:route.partner_id,page_path:page,city:'Escondido',intent:'NEW_SOLAR',cta_id:route.cta_id,timestamp:new Date(now).toISOString()};
function memory(){const data=new Map([['control/retention',{ok:true,checked_at:new Date(now).toISOString()}]]);return {data,get:async k=>data.get(k)??null,setJSON:async(k,v,o={})=>{if(!o.onlyIfNew||!data.has(k))data.set(k,structuredClone(v));},delete:async k=>data.delete(k),async *list(){yield {blobs:[...data.keys()].filter(k=>k.startsWith('events/')).map(key=>({key}))};}};}
function request(extra={},body={cid:event.cid,page_path:page,qualified:'1'}){return new Request('https://mygridpermit.com/go/compare-solar-prices',{method:'POST',headers:{origin:'https://mygridpermit.com','sec-fetch-site':'same-origin','content-type':'application/x-www-form-urlencoded','user-agent':'Mozilla/5.0',...extra},body:new URLSearchParams(body)});}
test('durable acknowledgment preserves exact CSP CID/ref/fragment; concurrent duplicate stores one event',async()=>{const store=memory(),handler=createOutboundHandler({routes:[route],getStore:()=>store,clock:()=>now});const results=await Promise.all(Array.from({length:10},()=>handler(request())));for(const res of results){assert.equal(res.status,303);const url=new URL(res.headers.get('location'));assert.equal(url.searchParams.get('cid'),event.cid);assert.equal(url.searchParams.get('ref'),'GridPermit');assert.equal(url.hash,'#quote');}assert.equal([...store.data.keys()].filter(k=>k.startsWith('events/')).length,1);assert.deepEqual(Object.keys(store.data.get(eventKey(event))).sort(),Object.keys(event).sort());});
test('server never trusts client territory/intent/destination or stores extra fields',async()=>{const store=memory(),handler=createOutboundHandler({routes:[route],getStore:()=>store,clock:()=>now});for(const body of [{cid:event.cid,page_path:page,qualified:'1',email:'blocked'},{cid:event.cid,page_path:'/california/mission-viejo/solar-permit-guide/',qualified:'1'},{cid:event.cid,page_path:page,qualified:'0'},{cid:'x',page_path:page,qualified:'1'}])assert.notEqual((await handler(request({},body))).status,303);assert.equal(store.data.size,1);});
test('bots, prefetch, cross-origin, duplicate fields and oversized bodies fail without writes',async()=>{const s=memory(),h=createOutboundHandler({routes:[route],getStore:()=>s,clock:()=>now});for(const headers of [{'user-agent':'Googlebot'},{purpose:'prefetch'},{origin:'https://evil.example'},{'sec-fetch-site':'cross-site'}])assert.equal((await h(request(headers))).status,403);assert.equal((await h(new Request('https://mygridpermit.com/go/compare-solar-prices'))).status,405);const req=request();const dup=new Request(req.url,{method:'POST',headers:req.headers,body:'cid='+event.cid+'&cid='+event.cid+'&page_path='+encodeURIComponent(page)+'&qualified=1'});assert.equal((await h(dup)).status,400);assert.equal((await h(request({}, {cid:'a'.repeat(700),page_path:page,qualified:'1'}))).status,400);assert.equal(s.data.size,1);});
test('storage failures, silent lost writes and capacity collision never claim recorded',async()=>{for(const kind of ['throws','lost','collision','retention']){const s=memory();if(kind==='throws')s.get=async()=>{throw new Error('storage down');};if(kind==='lost')s.setJSON=async()=>({modified:true});if(kind==='collision')s.data.set(eventKey(event),{...event,cid:'b'.repeat(24)});if(kind==='retention')s.data.set('control/retention',{ok:false});const h=createOutboundHandler({routes:[route],getStore:()=>s,clock:()=>now});const res=await h(request());assert.equal(res.status,303);assert.ok(['UNCONFIRMED','CAPACITY_COLLISION'].includes(res.headers.get('X-GridPermit-Recording')));}});
test('GPC and DNT preserve navigation without recording',async()=>{for(const key of ['sec-gpc','dnt']){const s=memory(),h=createOutboundHandler({routes:[route],getStore:()=>s,clock:()=>now});assert.equal((await h(request({[key]:'1'}))).headers.get('X-GridPermit-Recording'),'PRIVACY_OPT_OUT');assert.equal(s.data.size,1);}});
test('timeout does not break navigation or manufacture an acknowledgment',async()=>{const h=createOutboundHandler({routes:[route],getStore:()=>({get:()=>new Promise(()=>{})}),clock:()=>now,timeoutMs:5});assert.equal((await h(request())).headers.get('X-GridPermit-Recording'),'UNCONFIRMED');});
test('expired route cannot redirect; recording stages stay distinct',async()=>{const h=createOutboundHandler({routes:[{...route,valid_until:'2026-09-01T00:00:00Z'}],getStore:memory,clock:()=>now});assert.equal((await h(request())).status,410);assert.equal(new Set(STAGES).size,10);assert.deepEqual(STAGES.slice(-3),['COMMISSION_APPROVED','COMMISSION_PAYABLE','COMMISSION_PAID']);assert.ok(!('commission' in event));});
test('retention deletes expired events, preserves current data and disables writes on cleanup failure',async()=>{const s=memory(),old={...event,timestamp:'2026-09-19T00:00:00Z'};s.data.set(eventKey(old),old);s.data.set(eventKey(event),event);const result=await cleanupOutbound(s,now);assert.equal(result.deleted,1);assert.ok(s.data.has(eventKey(event)));s.delete=async()=>{throw new Error('delete unavailable');};s.data.set(eventKey(old),old);await assert.rejects(()=>cleanupOutbound(s,now));assert.equal(s.data.get('control/retention').ok,false);await assert.rejects(()=>recordOutbound(s,event,now));});
test('file-backed proof survives adapter restart and duplicate writes',async()=>{const dir=await mkdtemp(path.join(os.tmpdir(),'gp-outbound-'));const adapter=()=>({async get(k){try{return JSON.parse(await readFile(path.join(dir,k),'utf8'));}catch(e){if(e.code==='ENOENT')return null;throw e;}},async setJSON(k,v,o={}){const p=path.join(dir,k);await mkdir(path.dirname(p),{recursive:true});try{await writeFile(p,JSON.stringify(v),{flag:o.onlyIfNew?'wx':'w'});}catch(e){if(e.code!=='EEXIST')throw e;}}});try{await adapter().setJSON('control/retention',{ok:true,checked_at:new Date(now).toISOString()});assert.equal(await recordOutbound(adapter(),event,now),'RECORDED');assert.equal(await recordOutbound(adapter(),event,now),'DUPLICATE');assert.deepEqual(await adapter().get(eventKey(event)),event);}finally{await rm(dir,{recursive:true,force:true});}});
test('forensic holds cover disproven routes; canonical NorCal identity uses normal commercial gates',()=>{for(const p of [{partner_id:'stampedpv'},{name:'StampedPV'},{destination:'https://stampedpv.com'},{name:'Service Direct'},{partner_id:'solar-com',tracking:{network:'PARTNERIZE'}},{partner_id:'palmetto',tracking:{network:'IMPACT'}},{partner_id:'gogreensolar',tracking:{network:'SHAREASALE'}}])assert.ok(partnerEvidenceHold({...p,status:'ACTIVE'}));assert.equal(partnerEvidenceHold({partner_id:'norcal-solar-repair',name:'NorCal Solar Repair',tracking:{network:'DIRECT'}}),null);assert.equal(partnerEvidenceHold({partner_id:'energysage',tracking:{network:'CJ'}}),null);assert.equal(partnerEvidenceHold({partner_id:'palmetto',tracking:{network:'DIRECT'}}),null);});
