import {test} from 'node:test';import assert from 'node:assert/strict';import {performance} from 'node:perf_hooks';
import {createHash} from 'node:crypto';
import {readFile,mkdtemp,mkdir,writeFile,rm} from 'node:fs/promises';import path from 'node:path';import os from 'node:os';
import {importActivationBundle,importActivationCsv} from '../scripts/partner-import.mjs';
import {fingerprint,activationPlan} from '../scripts/lib/partner-config-io.mjs';
import {debugPartnerRoutes,partnerCities,PARTNER_STATUSES} from '../src/lib/commercial/partner-platform.ts';
import {AFFILIATE_NETWORKS} from '../src/lib/commercial/affiliate-adapters.ts';
import {buildCommercialOutbound} from '../src/lib/commercial/attribution.ts';
import {mergeApprovedBundle,sourceManifest,applyFactory,rollbackFactory,applyConfigChanges} from '../scripts/lib/factory-release.mjs';
import {inspectPartnerHtml} from '../scripts/partner-health.mjs';
import {coverageDelta} from '../scripts/lib/factory-context.mjs';
const NOW='2026-09-26T21:00:00Z';
const fingerprintBytes=value=>createHash('sha256').update(value).digest('hex');
const base=JSON.parse(await readFile(new URL('../data/commercial/partners/compare-solar-prices.json',import.meta.url)));
function fixture(){
 const p={...structuredClone(base),partner_id:'factory-fixture',name:'Local fixture',status:'APPROVED',placement:'PRIMARY',categories:['BATTERY_RETROFIT'],territories:{states:['CA'],cities:['richmond']},destination:'https://provider.example.com/battery/',paths:{solar:null,battery:'https://provider.example.com/battery/'},approval_reference:'fixture-approval',expected_hosts:['provider.example.com'],last_verified:'2026-09-25T00:00:00Z',qualification:{homeowner_required:true,confirmation_required:true,existing_solar:'ALLOW'},placements:[{page_path:'/california/richmond/solar-permit-guide/',record_id:'fixture-richmond',intent:'BATTERY_RETROFIT',review_reference:'fixture:review'}],program:{terms_reference:'fixture:terms',reverify_after:'2026-10-10T00:00:00Z',allowed_intents:['BATTERY_RETROFIT'],allowed_tracking_types:['CID_QUERY','UTM','PHONE_TRACKING'],excluded_cities:[],excluded_utilities:[],audience:'HOMEOWNER',allows_existing_solar:true}};
 const context={state:'CA',city:'Richmond',recordId:'fixture-richmond',utility:{value:'PG&E',notes:'Verified'},pagePath:'/california/richmond/solar-permit-guide/',pageType:'locality_guide',intent:'BATTERY_RETROFIT',pageIntent:'BATTERY_RETROFIT',existingSolar:true,batteryIntent:'RETROFIT'};
 const v={reference:p.approval_reference,partner_id:p.partner_id,reviewed:true,evidence_reference:'fixture:approval',approved_categories:p.categories,states:['CA'],cities:['richmond'],utilities:['VERIFIED_LOCAL_RECORD'],destinations:[p.destination],tracking_verified:true,approved_fallback:false,verified_at:'2026-09-25T00:00:00Z',expires_at:'2026-10-10T00:00:00Z',config_sha256:fingerprint(p)};
 const health=[{url:p.destination,finalUrl:p.destination,ok:true,status:200,checkedAt:NOW,queryPreserved:null}];
 const registry={partners:[p],verifications:[v],health,records:[{record_id:context.recordId,state:'CA',city:{value:'Richmond'},county:{value:'Contra Costa County'},utility:context.utility}]};return {p,v,health,registry,context,bundle:{schema_version:3,partners:[{config:p,verification:v,health}]}};
}
const renew=f=>{f.v.config_sha256=fingerprint(f.p);};
for(const status of PARTNER_STATUSES)test(`factory rejects non-APPROVED input: ${status}`,()=>{const f=fixture();f.p.status=status;if(status==='APPROVED')assert.equal(importActivationBundle(f.bundle,{now:NOW}).partners.length,1);else assert.throws(()=>importActivationBundle(f.bundle,{now:NOW}));});
test('strict importer rejects missing tracking, terms, expired proof, unreviewed data and extra contact column',()=>{for(const mutate of [f=>{f.p.tracking.active=false;},f=>{delete f.p.program;},f=>{f.v.expires_at='2026-09-01T00:00:00Z';},f=>{f.v.reviewed=false;},f=>{f.p.email='not-allowed';}]){const f=fixture();mutate(f);assert.throws(()=>importActivationBundle(f.bundle,{now:NOW}));}});
test('approved import stays inactive until explicit activation; merge does not mutate approval input',()=>{const f=fixture();assert.equal(debugPartnerRoutes(f.context,f.registry,NOW).selected,null);const result=mergeApprovedBundle(f.registry,importActivationBundle(f.bundle,{now:NOW}),{now:NOW});assert.equal(f.p.status,'APPROVED');assert.equal(result.registry.partners[0].status,'ACTIVE');assert.ok(debugPartnerRoutes(f.context,result.registry,NOW).selected);});
test('approval reference, scope, utility conflict and stale terms hard gates',()=>{for(const mutate of [f=>{f.p.approval_reference=null;},f=>{f.v.cities=[];},f=>{f.registry.records[0].utility.notes='City is split between multiple utilities';},f=>{f.p.program.reverify_after='2026-09-01T00:00:00Z';},f=>{f.p.program.excluded_cities=['richmond'];}]){const f=fixture();mutate(f);renew(f);assert.throws(()=>mergeApprovedBundle(f.registry,f.bundle,{now:NOW}));}});
test('county scope resolves canonical county and utility; statewide approval is independent',()=>{const f=fixture();f.p.territories={states:['CA'],cities:[],counties:[{state:'CA',county:'Contra Costa'}]};f.v.cities=[];f.v.counties=[{state:'CA',county:'Contra Costa County'}];renew(f);assert.deepEqual(partnerCities(f.p,f.registry.records),['richmond']);assert.ok(mergeApprovedBundle(f.registry,f.bundle,{now:NOW}));f.v.counties=[];assert.throws(()=>mergeApprovedBundle(f.registry,f.bundle,{now:NOW}));f.p.territories={states:['CA'],cities:[],statewide_verified:true};f.v.statewide_verified=true;renew(f);assert.ok(mergeApprovedBundle(f.registry,f.bundle,{now:NOW}));});
for(const network of AFFILIATE_NETWORKS)test(`configuration adapter: ${network}`,()=>{const f=fixture();const keys={CJ:'sid',IMPACT:'subId1',AWIN:'clickref',SHAREASALE:'afftrack',FLEXOFFERS:'subid',DIRECT:'subid'};f.p.tracking.network=network;f.p.tracking.cid_param=keys[network];renew(f);const merged=mergeApprovedBundle(f.registry,f.bundle,{now:NOW});const selected=debugPartnerRoutes(f.context,merged.registry,NOW).selected.selected;const u=new URL(buildCommercialOutbound(selected,'b'.repeat(24)));assert.equal(u.searchParams.get(keys[network]),'b'.repeat(24));});
test('backup needs approval then ACTIVE, and wins only when primary unavailable',()=>{const f=fixture(),primary={...structuredClone(f.p),partner_id:'fixture-primary',approval_reference:'primary-approval',status:'ACTIVE'};f.p.placement='BACKUP';f.registry.partners.push(primary);f.registry.verifications.push({...structuredClone(f.v),partner_id:primary.partner_id,reference:primary.approval_reference,config_sha256:fingerprint(primary)});renew(f);const merged=mergeApprovedBundle(f.registry,f.bundle,{now:NOW});assert.equal(debugPartnerRoutes(f.context,merged.registry,NOW).selected.partner_id,'fixture-primary');merged.registry.partners.find(p=>p.partner_id==='fixture-primary').status='PAUSED';assert.equal(debugPartnerRoutes(f.context,merged.registry,NOW).reason,'VERIFIED_BACKUP');});
for(const count of [50,100,250])test(`scale ${count}: deterministic routing, duplicate IDs rejected, no route explosion`,()=>{const f=fixture();f.p.status='ACTIVE';for(let n=1;n<count;n++){const p={...structuredClone(f.p),partner_id:'fixture-'+n,approval_reference:'approval-'+n,priority:10+n};f.registry.partners.push(p);f.registry.verifications.push({...structuredClone(f.v),partner_id:p.partner_id,reference:p.approval_reference,config_sha256:fingerprint(p)});}const start=performance.now(),first=debugPartnerRoutes(f.context,f.registry,NOW);f.registry.partners.reverse();const reversed=debugPartnerRoutes(f.context,f.registry,NOW);assert.equal(first.selected.partner_id,reversed.selected.partner_id);assert.equal(first.candidates.length,count);f.registry.partners.push(f.registry.partners[0]);assert.equal(debugPartnerRoutes(f.context,f.registry,NOW).reason,'INVALID_REGISTRY');console.log(JSON.stringify({benchmark:'factory-scale',partners:count,two_selections_ms:Math.round((performance.now()-start)*100)/100}));});
test('live crawler detects wrong partner, intent, missing visible disclosure and competing slot',()=>{const f=fixture(),selected=debugPartnerRoutes(f.context,mergeApprovedBundle(f.registry,f.bundle,{now:NOW}).registry,NOW).selected;const payload=JSON.stringify({selected:selected.selected}).replace(/&/g,'&amp;').replace(/"/g,'&quot;');const good=`<section data-partner-v2="${payload}"><p>${selected.selected.disclosure}</p></section>`;assert.deepEqual(inspectPartnerHtml(good,selected).errors,[]);assert.ok(inspectPartnerHtml(good.replace(/<p>.*?<\/p>/,''),selected).errors.includes('MISSING_DISCLOSURE'));assert.ok(inspectPartnerHtml(good+good,selected).errors.includes('DUPLICATE_PAID_SLOT'));assert.ok(inspectPartnerHtml(good,null).errors.includes('WRONG_PARTNER'));});
test('coverage delta keeps missing click evidence unknown',()=>{const d=coverageDelta([{page_path:'/x/',selected:null}],[{page_path:'/x/',selected:{partner_id:'one'}}]);assert.equal(d.expected_click_coverage,null);assert.equal(d.after_routes,1);assert.equal(d.changes.length,1);});
test('factory cannot apply a stale/tampered plan or canonical root',async()=>{const root=await mkdtemp(path.join(os.tmpdir(),'factory-plan-'));try{await mkdir(path.join(root,'.git'));await assert.rejects(()=>applyFactory({root,planFile:'does-not-exist'}),/isolated Git worktree/);}finally{await rm(root,{recursive:true,force:true});}});

test('automatic rollback restores exact local bytes and confirms prior production deploy',async()=>{const root=await mkdtemp(path.join(os.tmpdir(),'factory-rollback-'));try{await mkdir(path.join(root,'data'),{recursive:true});const file=path.join(root,'data','partner.json'),old=Buffer.from('{"status":"SHADOW"}\n'),applied=Buffer.from('{"status":"ACTIVE"}\n');await writeFile(file,applied);const calls=[];const execute=async(command,args)=>{calls.push([command,...args]);if(args.includes('getSite'))return JSON.stringify({id:'d49c19aa-f997-43f3-9b11-fabff36c4c83',published_deploy:{id:'prior-deploy',state:'ready'}});return '{}';};const result=await rollbackFactory({root,journal:[{path:'data/partner.json',old_bytes_base64:old.toString('base64'),applied_sha256:fingerprintBytes(applied)}],expectedDeploy:'prior-deploy',productionDeployed:true,execute});assert.equal((await readFile(file,'utf8')),'{"status":"SHADOW"}\n');assert.equal(result.production_restored,true);assert.ok(calls.some(x=>x.includes('restoreSiteDeploy')));}finally{await rm(root,{recursive:true,force:true});}});

test('new approved configuration registers report adapter and call duration never creates payment',async()=>{const {reportAdaptersFromPartners,normalizeCallReport}=await import('../scripts/lib/partner-measurement.mjs');const f=fixture(),adapters=reportAdaptersFromPartners([f.p]);const row={cid:'a'.repeat(24),stage:'QUALIFIED',channel:'PAY_PER_CALL',reported_at:NOW,amount_cents:null,currency:null,evidence_ref:'fixture:report',payment_evidence_ref:null,partner_event_id:'fixture:event',call_duration_seconds:90};const campaign={campaign_active:true,minimum_call_seconds:90};assert.equal(normalizeCallReport(f.p.partner_id,[row],campaign,adapters)[0].amount_cents,null);assert.throws(()=>normalizeCallReport(f.p.partner_id,[{...row,call_duration_seconds:89}],campaign,adapters));assert.throws(()=>normalizeCallReport(f.p.partner_id,[{...row,caller_phone:'not-allowed'}],campaign,adapters));});


test('configuration application writes each path once and its journal restores exact previous bytes',async()=>{
 const root=await mkdtemp(path.join(os.tmpdir(),'factory-once-'));
 try {
  const staging=path.join(root,'staging'),relative='data/partner.json',old=Buffer.from('{"status":"SHADOW"}\n');
  await mkdir(path.join(root,'data'),{recursive:true});await mkdir(path.join(staging,'data'),{recursive:true});
  await writeFile(path.join(root,relative),old);await writeFile(path.join(staging,relative),JSON.stringify({status:'ACTIVE'},null,2)+'\n');
  const journal=[],journalFile=path.join(root,'journal.json'),args={root,staging,changes:[relative],sourceBeforeFiles:[{path:relative,sha256:fingerprintBytes(old)}],journal,journalFile};
  await applyConfigChanges(args);assert.equal(journal.length,1);assert.equal(JSON.parse(await readFile(path.join(root,relative),'utf8')).status,'ACTIVE');
  assert.equal(journal[0].applied_sha256,fingerprintBytes(await readFile(path.join(root,relative))));
  await rollbackFactory({root,journal});assert.deepEqual(await readFile(path.join(root,relative)),old);
  await assert.rejects(()=>applyConfigChanges({...args,changes:[relative,relative]}),/Duplicate configuration path/);
  assert.deepEqual(await readFile(path.join(root,relative)),old);
 }finally{await rm(root,{recursive:true,force:true});}
});
